version: '3'

services:
  api:
    restart: always
    container_name: api
    build: ./api
    ports:
      - "5555:5000"
    depends_on:
      - mysql
  frontend:
    restart: always
    container_name: frontend
    build: ./frontend
    ports:
      - "8954:8954"
  mysql:
    restart: always
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db 
    ports:
      - "3306:3306"  
